-- Intentionally empty: the flashcards table (supabase/migrations/) has no
-- fixture data yet. See README.md's Supabase Configuration section.
-- Referenced by supabase/config.toml's db.seed.sql_paths.
